---
title: "Digital Portfolio"
author: "Aiden O'Neill"
date: "10/27/2020"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
---

```{r Setup}
#Setting up dataset to use in following chunks

sPerformanceMaths=read.table("student-mat.csv",sep=";",header=TRUE)
sPerformancePor=read.table("student-por.csv",sep=";",header=TRUE)

sPerformanceMerged=merge(sPerformanceMaths,sPerformancePor,by=c("school","sex","age","address","famsize","Pstatus","Medu","Fedu","Mjob","Fjob","reason","nursery","internet"))
print(nrow(sPerformanceMerged)) # 382 students

needed_packages <- c("pastecs", "ggplot2", "semTools", "FSA", "car", "effectsize", "userfriendlyscience", "rstatix", "sjstats", "gmodels")                                    
# Extract not installed packages
not_installed <- needed_packages[!(needed_packages %in% installed.packages()[ , "Package"])]    
# Install not installed packages
if(length(not_installed)) install.packages(not_installed)                            
library(pastecs) #For creating descriptive statistic summaries
library(ggplot2) #For creating histograms with more detail than plot
library(semTools) #For skewness and kurtosis
library(FSA)
library(car) # For Levene's test for homogeneity of variance 
library(effectsize) #To calculate effect size for t-test
library(userfriendlyscience)
library(rstatix)#Kruskal wallis effect size
library(sjstats)#chi-square effect size
library(gmodels)#chi-square effect size

```

## R Markdown

```{r Analyse Step Correlation - G2.y ~ G3.x}
gm <- ggplot(sPerformanceMerged, aes(G2.y,G3.x))
gm <- gm + geom_point(colour = "Blue") + geom_smooth(method = "lm", colour = "Blue", se = F)
gm

scatterplot(G3.x~G2.y, regLine=FALSE, smooth=list(span=1, spread=FALSE), 
  boxplots=FALSE, data=sPerformanceMerged)

cor.test(sPerformanceMerged$G2.y, sPerformanceMerged$G3.x, method='pearson')

cor.test(sPerformanceMerged$G2.y, sPerformanceMerged$G3.x, method = "spearman")

cor.test(sPerformanceMerged$G2.y, sPerformanceMerged$G3.x, method = "kendall")
```

```{r Analyse Step Correlation First Math Grade ~ Final Math Grade}
gm <- ggplot(sPerformanceMerged, aes(G1.x,G3.x))
gm <- gm + geom_point(colour = "Blue") + geom_smooth(method = "lm", colour = "Blue", se = F)
gm

scatterplot(G1.x~G3.x, regLine=FALSE, smooth=FALSE, boxplots=FALSE, 
  data=sPerformanceMerged)

cor.test(sPerformanceMerged$G1.x, sPerformanceMerged$G3.x, method='pearson')

cor.test(sPerformanceMerged$G1.x, sPerformanceMerged$G3.x, method = "spearman")

cor.test(sPerformanceMerged$G1.x, sPerformanceMerged$G3.x, method = "kendall")

```

### Romantic.x Generate histogram
```{r}

#We will allocate the histogram to a variable to allow use to manipulate it
gg <- ggplot(sPerformanceMerged, aes(x=G3.x))

#Change the label of the x axis
gg <- gg + labs(x="Final Maths Grade")

#manage binwidth and colours
gg <- gg + geom_histogram(binwidth=2, colour="black", aes(y=..density.., fill=..count..))
gg <- gg + scale_fill_gradient("Count", low="#DCDCDC", high="#7C7C7C")

gg <- gg + stat_function(fun=dnorm, color="red",args=list(mean=mean(sPerformanceMerged$G3.x, na.rm=TRUE), sd=sd(sPerformanceMerged$G3.x, na.rm=TRUE)))

#to display the graph request the contents of the variable be shown
gg
```
### G3.x Generate Q-Q Plot
```{r}
#Create a qqplot
qqnorm(sPerformanceMerged$G3.x)
qqline(sPerformanceMerged$G3.x, col=2) #show a line on theplot
```


### G3.x Generate Summary Statistics 
```{r}
pastecs::stat.desc(sPerformanceMerged$G3.x, basic=F)

tpskew<-semTools::skew(sPerformanceMerged$G3.x)
tpkurt<-semTools::kurtosis(sPerformanceMerged$G3.x)
tpskew[1]/tpskew[2]

tpkurt[1]/tpkurt[2]

zG3x<- abs(scale(sPerformanceMerged$G3.x))

FSA::perc(as.numeric(zG3x), 1.96, "gt")
FSA::perc(as.numeric(zG3x), 3.29, "gt")

```

### Differences - Parametric Tests
#### Independent t-test
##### Describe G3.x Grade by group (Relationship v non-Relationship - variable romantic.x)
```{r Describe}
#Get descriptive stastitics by group - output as a matrix
psych::describeBy(sPerformanceMerged$G3.x, sPerformanceMerged$romantic.x, mat=TRUE)

#Conduct Levene's test for homogeneity of variance in library car - the null hypothesis is that variances in groups are equal so to assume homogeneity we woudl expect probaility to not be statistically significant.
car::leveneTest(G3.x ~ romantic.x, data=sPerformanceMerged)
#Pr(>F) is your probability - in this case it is not statistically significant so we can assume homogeneity

stats::t.test(G3.x~romantic.x,var.equal=TRUE,data=sPerformanceMerged)

res <- stats::t.test(G3.x~romantic.x,var.equal=TRUE,data=sPerformanceMerged)
#Calculate Cohen's d
#artithmetically
effcd=round((2*res$statistic)/sqrt(res$parameter),2)
effcd
#Using function from effectsize package
effectsize::t_to_d(t = res$statistic, res$parameter)


#Eta squared calculation
effes=round((res$statistic*res$statistic)/((res$statistic*res$statistic)+(res$parameter)),3)
effes


```

```{r NON Parametric test - difference}

#Get your descriptive statistcs
by(sPerformanceMerged$G3.y,sPerformanceMerged$internet, median)
by(sPerformanceMerged$G3.y,sPerformanceMerged$internet, IQR)

#Create plots of these
gs <- ggplot(sPerformanceMaths, aes(x=G3))
gs <- gs + ggtitle ("Final Grade of Subject")
gs <- gs + labs(x="Maths")
gs <- gs + geom_histogram(binwidth=2, colour="black")
gs <- gs + scale_fill_gradient("Count", low="#DCDCDC", high="#7C7C7C")
gs <- gs + stat_function(fun=dnorm, color="red",args=list(mean=mean(sPerformanceMaths$G3, na.rm=TRUE), sd=sd(sPerformanceMaths$G3, na.rm=TRUE)))
gs

gs <- ggplot(sPerformancePor, aes(x=G3))
gs <- gs + ggtitle ("Final Grade of Subject")
gs <- gs + labs(x="Portuguese")
gs <- gs + geom_histogram(binwidth=2, colour="black")
gs <- gs + scale_fill_gradient("Count", low="#DCDCDC", high="#7C7C7C")
gs <- gs + stat_function(fun=dnorm, color="red",args=list(mean=mean(sPerformancePor$G3.y, na.rm=TRUE), sd=sd(sPerformancePor$G3, na.rm=TRUE)))
gs

stats::wilcox.test(G3.y~internet, data=sPerformanceMerged) 

coin::wilcox_test(G3.y~as.factor(internet), data=sPerformanceMerged)

reff=rstatix::wilcox_effsize(G3.y~internet, data=sPerformanceMerged)

reff$effsize

```

```{r ANOVA one way, Mjob and final math grade}
psych::describeBy(sPerformanceMerged$G3.x, sPerformanceMerged$Mjob, mat=TRUE)
stats::bartlett.test(G3.x~ Mjob, data=sPerformanceMerged)
userfriendlyscience::oneway(as.factor(sPerformanceMerged$Mjob),y=sPerformanceMerged$G3.x,posthoc='Tukey')
res2<-stats::aov(G3.x~ Mjob, data = sPerformanceMerged)
fstat<-summary(res2)[[1]][["F value"]][[1]]
aovpvalue<-summary(res2)[[1]][["Pr(>F)"]][[1]]
aoveta<-sjstats::eta_sq(res2)[2]

```

```{r kruskal wallis test for reason a student attended and studytime}

psych::describeBy(as.numeric(sPerformanceMerged$studytime.x),factor(sPerformanceMerged$reason) )
stats::kruskal.test(studytime.x~reason,data=sPerformanceMerged)
tmp<-FSA::dunnTest(x=as.numeric(sPerformanceMerged$studytime.x), g=factor(sPerformanceMerged$reason), method="bonferroni") 
print(tmp, dunn.test.results = TRUE)
rstatix::kruskal_effsize(sPerformanceMerged, studytime.x~reason, ci = FALSE, conf.level = 0.95,
  ci.type = "perc", nboot = 1000)#uses bootstrapping

```

```{r Difference Nominal}
#Use the Crosstable function
#CrossTable(predictor, outcome, fisher = TRUE, chisq = TRUE, expected = TRUE)
gmodels::CrossTable(sPerformanceMerged$sex, sPerformanceMerged$activities.x, fisher = TRUE, chisq = TRUE, expected = TRUE, sresid = TRUE, format = "SPSS")

#more simplistic way of doing Chi-Square

#Create your contingency table
mytable<-xtabs(~activities.x+sex, data=sPerformanceMerged)

ctest<-stats::chisq.test(mytable, correct=TRUE)#chi square test
#correct=TRUE to get Yates correction needed for 2x2 table

ctest#will give you the details of the test statistic and p-value
ctest$expected#expected frequencies
ctest$observed#observed frequencies
ctest$p.value
#Calculate effect size
sjstats::phi(mytable)
sjstats::cramer(mytable)

```

```{r Repeated Measure T-test}
#Paired T-test:
summary(sPerformanceMerged$G2.x)
summary(sPerformanceMerged$G3.x)
sd(sPerformanceMerged$G2.x)
sd(sPerformanceMerged$G3.x)
t.test(sPerformanceMerged$G3.x,sPerformanceMerged$G2.x,paired=TRUE)

res <- stats::t.test(sPerformanceMerged$G3.x,sPerformanceMerged$G2.x,paired=TRUE)
#Calculate Cohen's d
#artithmetically
effcd=round((2*res$statistic)/sqrt(res$parameter),2)
effcd
#Using function from effectsize package
effectsize::t_to_d(t = res$statistic, res$parameter)


#Eta squared calculation
effes=round((res$statistic*res$statistic)/((res$statistic*res$statistic)+(res$parameter)),3)
effes
```